### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by gkzsolt** [corvasto/codecogs-latex-chrome-extension#1]
Garbel, this is awesome! Thank you so much.

Take note: the url of CodeCogs changed a bit, so I updated the code on my part. I also changed it to use larger font size on the rendered equation.

All the best,
    Zsolt

**Comment by corvasto** [comment]
Thanks @gkzsolt, glad it helped!
Didn't know that the url changed. I've updated the code here as well with the working url.
CodeCogs docs: https://editor.codecogs.com/docs/
